# yaml-language-server: $schema=https://schema.innerknowing.xyz/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: hyprland-latest

# description will be included in the image's metadata
description: ublue images for wayland compositors

base-image: quay.io/fedora-ostree-desktops/base-atomic

image-version: 42 

modules:
  - from-file: common/sddm-modules.yml
  - from-file: common/common-modules.yml
  - from-file: common/hyprland-modules.yml
  - from-file: common/flatpak.yml
  - from-file: common/fonts.yml
  - from-file: common/final-modules.yml
